### ISSUE TITLE
表示のバグ

### ISSUE THREAD

**Issue by zutomayo147** [xyzyxJP/GakujoGUI-WPF#30]
**不具合について**  

GUIの表示がおかしい気がする。また、ログインできない。

**再現方法について**  

v1.3.4.9を実行

**予想される動作について**  

GUIの表示がおかしい気がする。

**スクリーンショット**  

<img width="671" alt="スクリーンショット 2022-05-17 045848" src="https://user-images.githubusercontent.com/42014197/168681039-88315f5a-6c30-411d-84dc-4d3eea24b0f4.png">

<img width="677" alt="スクリーンショット 2022-05-17 045926" src="https://user-images.githubusercontent.com/42014197/168681064-8cc975dc-ecc4-452d-9da8-0736b3630f94.png">

**パソコンスペック**  

Win11 生協PC 2022年度

**GakujoGUIの設定**  

初期設定

**Comment by xyzyxJP** [comment]
背景画像が未設定の一部の場合に，背景が正しく描画されないバグについては[v1.3.5.0](https://github.com/xyzyxJP/GakujoGUI-WPF/releases/tag/v1.3.5.0)で修正しました．
ログインできないバグについては`%appdata%/GakujoGUI/Logs`に保存されるログを添付してください．

**Comment by xyzyxJP** [comment]
承知しました．
